apiVersion: apps/v1
kind: Deployment
metadata:
  name: gem
  labels:
    app: gem
spec:
  selector:
    matchLabels:
      app: gem
      tier: web
  template:
    metadata:
      labels:
        app: gem
        tier: web
    spec:
      containers:
        - name: gem
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - containerPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: streamlitweb-backend
  labels:
    app: gem
spec:
  type: LoadBalancer
  selector:
    app: gem
    tier: web
  ports:
    - port: 80
      targetPort: 8501
