# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - g-e-m-l

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_f1d968718b8d472694eaeaf0a91b1467 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_dc95e80c77cc4cbd98b29075c13b2e7a }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f1d968718b8d472694eaeaf0a91b1467 }}/gem:${{ github.sha }}
          file: ./Dockerfile

    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'g-e-m-l'
            slot-name: 'production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_30a539cca72c405699bfb88fc252ca89 }}
            images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f1d968718b8d472694eaeaf0a91b1467 }}/gem:${{ github.sha }}'
